title: 悟文佛经学习群
author:
  name: 悟文
  email: yuwen.song@outlook.com
description: >
  道不可不作，经不可不学！
permalink: /sutra/:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: false
minima:
  skin: classic
  date_format: "%Y/%m/%d"
